### ISSUE TITLE
Command line docs not up to date

### ISSUE THREAD

**Issue by andre2007** [dlang/dub-docs#8]
As far as I understand the command line docs are automatically generated by executing dub. The changes I 've done in June are not reflected in the documentation.

https://github.com/dlang/dub/commit/18a3858c582faaea0da5176ca85ce8ac243db8b3

**Comment by wilzbach** [comment]
I think all that's needed is to bump dub here:

https://github.com/dlang/dub-docs/blob/master/dub.sdl

Or maybe simply set it to master...

**Comment by andre2007** [comment]
Unfortunately that will lead to syntax errors at the moment due to the nonet bug
https://github.com/dlang/dub/issues/1558

HttpStatusException is used in code but not available in config nonet.

**Comment by wilzbach** [comment]
Thanks a lot for noticing!
